spring:
  datasource:
    # 数据库选择8,要使用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comm?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 582552546
  mail:
    host: smtp.163.com
    port: 587
    username: uuhhmail@163.com
    password: GEQOIXGRZENRFJDA
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    protocol: smtp
    default-encoding: utf-8

# 配置mybatis-plus的日志信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
server:
  servlet:
    context-path: /
  port: 8080
debug: true

logging:
  pattern:
    console: "%d - %msg%n"
  file:
    path:  "/Code_Study/Project/newCoder/src/main/resources/log/"

# 配置域名之类的，自定义的
community.path.domain: http://localhost:8080
community.path.upload: E:\Code_Study\Project\upload